name: Feature Request
description: Suggest an enhancement for TimeTrack
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
        Please include the ⚡ emoji at the start of your title if you've read our contributing guidelines.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem would this feature solve?
      placeholder: I'm always frustrated when trying to track...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What solution would you like to see?
      placeholder: Describe your ideal solution in detail
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
    validations:
      required: false
      
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mock-ups, or screenshots about the feature request here.
    validations:
      required: false
      
  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      options:
        - label: I would be willing to implement this feature myself
